/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects_.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as BlogTagSlugRouteImport } from './routes/blog_.tag.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog_.category.$slug'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects_.new'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog_.new'
import { Route as AdminProjectsIdEditRouteImport } from './routes/admin.projects_.$id.edit'
import { Route as AdminBlogIdEditRouteImport } from './routes/admin.blog_.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects_/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/blog_/tag/$slug',
  path: '/blog/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog_/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/projects_/new',
  path: '/projects/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog_/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIdEditRoute = AdminProjectsIdEditRouteImport.update({
  id: '/projects_/$id/edit',
  path: '/projects/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdEditRoute = AdminBlogIdEditRouteImport.update({
  id: '/blog_/$id/edit',
  path: '/blog/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/projects_/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog_/new': typeof AdminBlogNewRoute
  '/admin/projects_/new': typeof AdminProjectsNewRoute
  '/blog_/category/$slug': typeof BlogCategorySlugRoute
  '/blog_/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog_/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/projects_/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/login'
    | '/admin/projects'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/admin/blog/new'
    | '/admin/projects/new'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog/$id/edit'
    | '/admin/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/login'
    | '/admin/projects'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/admin'
    | '/admin/blog/new'
    | '/admin/projects/new'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog/$id/edit'
    | '/admin/projects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/login'
    | '/admin/projects'
    | '/blog_/$slug'
    | '/projects_/$slug'
    | '/admin/'
    | '/admin/blog_/new'
    | '/admin/projects_/new'
    | '/blog_/category/$slug'
    | '/blog_/tag/$slug'
    | '/admin/blog_/$id/edit'
    | '/admin/projects_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects_/$slug': {
      id: '/projects_/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog_/tag/$slug': {
      id: '/blog_/tag/$slug'
      path: '/blog/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/category/$slug': {
      id: '/blog_/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects_/new': {
      id: '/admin/projects_/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog_/new': {
      id: '/admin/blog_/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects_/$id/edit': {
      id: '/admin/projects_/$id/edit'
      path: '/projects/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminProjectsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog_/$id/edit': {
      id: '/admin/blog_/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AdminBlogIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminBlogIdEditRoute: typeof AdminBlogIdEditRoute
  AdminProjectsIdEditRoute: typeof AdminProjectsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminBlogIdEditRoute: AdminBlogIdEditRoute,
  AdminProjectsIdEditRoute: AdminProjectsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
